export type MenuCategory = 'a_la_carte' | 'dolci' | 'vini' | 'bibite' | 'fuori_menu';

export type MenuSubCategory =
  | 'Antipasti'
  | 'Primi Piatti'
  | 'Secondi & Carni'
  | 'Contorni'
  | 'Dolci & Dessert'
  | 'Vini Rossi'
  | 'Vini Bianchi & Bollicine'
  | 'Prosecco & Champagne'
  | 'Acque & Bibite'
  | 'Caffè & Digestivi'
  | 'Special dello Chef (Fuori Menù)';

export interface MenuItem {
  id: string;
  name: string;
  category: MenuCategory;
  subCategory: MenuSubCategory;
  price: number;
  glassPrice?: number;
  bottlePrice?: number;
  cost?: number;
  destination: 'kitchen' | 'bar';
  isMeat?: boolean;
  isVegetarian?: boolean;
  containsNuts?: boolean;
  isAvailable: boolean; // false = 86'd / esaurito
  description?: string;
  allergens?: string[];
  orderCount: number;
  revenueGenerated: number;
  createdAt: string;
  updatedAt: string;
}

const MENU_STORAGE_KEY = 'sotto_sotto_official_menu_v1';

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // =========================================================================
  // 1. PER COMINCIARE (TO START / ANTIPASTI)
  // =========================================================================
  {
    id: 'ant_1',
    name: 'Bruschetta ai gamberoni',
    category: 'a_la_carte',
    subCategory: 'Antipasti',
    price: 12.75,
    cost: 3.8,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: false,
    containsNuts: false,
    isAvailable: true,
    description: 'Marinated king prawns tossed with an infusion of Mediterranean flavours and fresh chilli on Sotto Sotto focaccia bread.',
    allergens: ['Crostacei', 'Glutine'],
    orderCount: 84,
    revenueGenerated: 1071.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'ant_2',
    name: 'Portobello alla griglia con caprino',
    category: 'a_la_carte',
    subCategory: 'Antipasti',
    price: 11.75,
    cost: 3.2,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: true,
    isAvailable: true,
    description: 'Grilled portobello mushroom topped with crumbled goat cheese, walnuts and aged balsamic reduction (v) (n)',
    allergens: ['Lattosio', 'Frutta a guscio'],
    orderCount: 62,
    revenueGenerated: 728.5,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'ant_3',
    name: 'Calamaretti fritti ai sette sapori',
    category: 'a_la_carte',
    subCategory: 'Antipasti',
    price: 12.00,
    cost: 3.5,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: false,
    containsNuts: false,
    isAvailable: true,
    description: 'Seven herb crisp and tender squid with a delicate garlic aioli',
    allergens: ['Molluschi', 'Glutine', 'Uova'],
    orderCount: 96,
    revenueGenerated: 1152.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'ant_4',
    name: 'Baccalà impanato con salsa Pizzaiola',
    category: 'a_la_carte',
    subCategory: 'Antipasti',
    price: 12.50,
    cost: 3.6,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: false,
    containsNuts: false,
    isAvailable: true,
    description: 'Breaded cod pieces with tomato sauce, oregano, basil, onions and garlic',
    allergens: ['Pesce', 'Glutine'],
    orderCount: 58,
    revenueGenerated: 725.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'ant_5',
    name: 'Cicchetti della casa',
    category: 'a_la_carte',
    subCategory: 'Antipasti',
    price: 13.75,
    cost: 4.5,
    destination: 'kitchen',
    isMeat: true,
    isVegetarian: false,
    containsNuts: false,
    isAvailable: true,
    description: 'A selection of imported venison bresaola, wild boar salame, speck, cheese and grilled marinated vegetables',
    allergens: ['Lattosio'],
    orderCount: 112,
    revenueGenerated: 1540.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'ant_6',
    name: 'Bruschetta con zucca, caprino e noci',
    category: 'a_la_carte',
    subCategory: 'Antipasti',
    price: 11.50,
    cost: 3.0,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: true,
    isAvailable: true,
    description: 'Toasted Tuscan bread with roasted butternut squash, walnuts and goat cheese mousse (v) (n)',
    allergens: ['Lattosio', 'Frutta a guscio', 'Glutine'],
    orderCount: 48,
    revenueGenerated: 552.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },

  // =========================================================================
  // 2. I FARINACEI (PASTA & RISOTTO)
  // =========================================================================
  {
    id: 'pri_1',
    name: 'Linguine con gamberi',
    category: 'a_la_carte',
    subCategory: 'Primi Piatti',
    price: 18.25,
    cost: 5.2,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: false,
    containsNuts: false,
    isAvailable: true,
    description: 'Linguine tossed with prawns, sun-dried tomatoes, anchovies, black olives, capers, garlic and EVO oil',
    allergens: ['Crostacei', 'Pesce', 'Glutine'],
    orderCount: 135,
    revenueGenerated: 2463.75,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'pri_2',
    name: 'Penne con funghi, noci e Gorgonzola',
    category: 'a_la_carte',
    subCategory: 'Primi Piatti',
    price: 17.75,
    cost: 4.8,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: true,
    isAvailable: true,
    description: 'Penne pasta with mushrooms, walnuts and Gorgonzola cheese (v) (n)',
    allergens: ['Lattosio', 'Frutta a guscio', 'Glutine'],
    orderCount: 92,
    revenueGenerated: 1633.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'pri_3',
    name: 'Fettucce alla crema di zucca',
    category: 'a_la_carte',
    subCategory: 'Primi Piatti',
    price: 18.25,
    cost: 5.0,
    destination: 'kitchen',
    isMeat: true,
    isVegetarian: false,
    containsNuts: false,
    isAvailable: true,
    description: 'Fettucce pasta with sage, chilli, roasted butternut squash, diced salt-cured pork belly and truffle cream',
    allergens: ['Glutine', 'Lattosio'],
    orderCount: 110,
    revenueGenerated: 2007.5,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'pri_4',
    name: 'Fettucce al ragù di manzo con fonduta di Pecorino',
    category: 'a_la_carte',
    subCategory: 'Primi Piatti',
    price: 18.75,
    cost: 5.5,
    destination: 'kitchen',
    isMeat: true,
    isVegetarian: false,
    containsNuts: false,
    isAvailable: true,
    description: 'Fettucce pasta with beef ragout on a bed of Pecorino cheese fondue',
    allergens: ['Glutine', 'Lattosio'],
    orderCount: 145,
    revenueGenerated: 2718.75,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'pri_5',
    name: 'Penne alla vodka',
    category: 'a_la_carte',
    subCategory: 'Primi Piatti',
    price: 17.75,
    cost: 4.6,
    destination: 'kitchen',
    isMeat: true,
    isVegetarian: false,
    containsNuts: false,
    isAvailable: true,
    description: 'Penne pasta, diced salt-cured pork belly, onions, fresh tomato sauce, cream and vodka',
    allergens: ['Glutine', 'Lattosio'],
    orderCount: 88,
    revenueGenerated: 1562.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'pri_6',
    name: 'Risotto con zucchine e salmone',
    category: 'a_la_carte',
    subCategory: 'Primi Piatti',
    price: 17.95,
    cost: 5.2,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: false,
    containsNuts: false,
    isAvailable: true,
    description: 'Italian arborio rice risotto with courgettes, smoked and fresh salmon, lemon zest and a touch of Pinot Grigio',
    allergens: ['Pesce', 'Lattosio'],
    orderCount: 79,
    revenueGenerated: 1418.05,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },

  // =========================================================================
  // 3. LE SPECIALITA' (SPECIALITIES / SECONDI)
  // =========================================================================
  {
    id: 'sec_1',
    name: 'Pollo e salsiccia',
    category: 'a_la_carte',
    subCategory: 'Secondi & Carni',
    price: 22.00,
    cost: 6.5,
    destination: 'kitchen',
    isMeat: true,
    isVegetarian: false,
    containsNuts: false,
    isAvailable: true,
    description: 'Strips of chicken breast and italian sausage in sautéed white wine, rosemary, garlic and aged balsamic vinegar',
    allergens: [],
    orderCount: 118,
    revenueGenerated: 2596.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'sec_2',
    name: 'Bistecca di manzo con crema di funghi',
    category: 'a_la_carte',
    subCategory: 'Secondi & Carni',
    price: 31.00,
    cost: 9.8,
    destination: 'kitchen',
    isMeat: true,
    isVegetarian: false,
    containsNuts: false,
    isAvailable: true,
    description: '10oz grilled sirloin of beef with red wine sauce and mushroom cream',
    allergens: ['Lattosio'],
    orderCount: 125,
    revenueGenerated: 3875.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'sec_3',
    name: 'Filetto di manzo in crosta di pistacchi',
    category: 'a_la_carte',
    subCategory: 'Secondi & Carni',
    price: 33.75,
    cost: 11.2,
    destination: 'kitchen',
    isMeat: true,
    isVegetarian: false,
    containsNuts: true,
    isAvailable: true,
    description: 'Pistachio crusted 7oz fillet of beef with mixed root vegetables and Primitivo red wine sauce (n)',
    allergens: ['Frutta a guscio'],
    orderCount: 160,
    revenueGenerated: 5400.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'sec_4',
    name: 'Pesce spada al salmoriglio',
    category: 'a_la_carte',
    subCategory: 'Secondi & Carni',
    price: 24.50,
    cost: 7.5,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: false,
    containsNuts: false,
    isAvailable: true,
    description: 'Fresh grilled swordfish, roasted vegetables, and salmoriglio sauce',
    allergens: ['Pesce'],
    orderCount: 72,
    revenueGenerated: 1764.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'sec_5',
    name: 'Branzino in crosta di noci',
    category: 'a_la_carte',
    subCategory: 'Secondi & Carni',
    price: 25.25,
    cost: 7.8,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: false,
    containsNuts: true,
    isAvailable: true,
    description: 'Walnut-crusted fresh sea bass with roasted potatoes, black olives, red onion and cherry tomatoes (n)',
    allergens: ['Pesce', 'Frutta a guscio'],
    orderCount: 86,
    revenueGenerated: 2171.5,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'sec_6',
    name: 'Salmone alla mostarda',
    category: 'a_la_carte',
    subCategory: 'Secondi & Carni',
    price: 24.25,
    cost: 7.2,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: false,
    containsNuts: false,
    isAvailable: true,
    description: 'Grilled fresh salmon with whole grain mustard and shallots in a creamy sauce',
    allergens: ['Pesce', 'Senape', 'Lattosio'],
    orderCount: 65,
    revenueGenerated: 1576.25,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'sec_7',
    name: 'Polenta grigliata con zucca e Pecorino',
    category: 'a_la_carte',
    subCategory: 'Secondi & Carni',
    price: 17.25,
    cost: 4.2,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: false,
    isAvailable: true,
    description: 'Chargrilled polenta with roasted butternut squash and pecorino cheese (v)',
    allergens: ['Lattosio'],
    orderCount: 42,
    revenueGenerated: 724.5,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },

  // =========================================================================
  // 4. I CONTORNI (SIDE DISHES)
  // =========================================================================
  {
    id: 'con_1',
    name: 'Patate arrosto al rosmarino',
    category: 'a_la_carte',
    subCategory: 'Contorni',
    price: 5.50,
    cost: 1.2,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: false,
    isAvailable: true,
    description: 'Rosemary roasted potatoes',
    allergens: [],
    orderCount: 195,
    revenueGenerated: 1072.5,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'con_2',
    name: 'Spinaci al Parmigiano',
    category: 'a_la_carte',
    subCategory: 'Contorni',
    price: 5.50,
    cost: 1.4,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: false,
    isAvailable: true,
    description: 'Sautéed spinach, garlic and EV olive oil sprinkled with parmesan',
    allergens: ['Lattosio'],
    orderCount: 130,
    revenueGenerated: 715.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'con_3',
    name: 'Insalata mista',
    category: 'a_la_carte',
    subCategory: 'Contorni',
    price: 5.50,
    cost: 1.1,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: false,
    isAvailable: true,
    description: 'Sotto Sotto garden salad',
    allergens: [],
    orderCount: 88,
    revenueGenerated: 484.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'con_4',
    name: 'Verdure miste',
    category: 'a_la_carte',
    subCategory: 'Contorni',
    price: 5.50,
    cost: 1.3,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: false,
    isAvailable: true,
    description: 'Fresh roasted mixed vegetables',
    allergens: [],
    orderCount: 104,
    revenueGenerated: 572.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },

  // =========================================================================
  // 5. PECCATI DI GOLA (DESSERTS & CHEESE)
  // =========================================================================
  {
    id: 'dol_1',
    name: 'Mousse al cioccolato e Amaretto Disaronno',
    category: 'dolci',
    subCategory: 'Dolci & Dessert',
    price: 9.75,
    cost: 2.5,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: true,
    isAvailable: true,
    description: 'Amaretto Disaronno and dark chocolate mousse (n)',
    allergens: ['Frutta a guscio', 'Lattosio', 'Uova'],
    orderCount: 110,
    revenueGenerated: 1072.5,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'dol_2',
    name: 'Semifreddo alla nocciola',
    category: 'dolci',
    subCategory: 'Dolci & Dessert',
    price: 9.50,
    cost: 2.4,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: true,
    isAvailable: true,
    description: 'Hazelnut semifreddo with chocolate sauce (n)',
    allergens: ['Frutta a guscio', 'Lattosio', 'Uova'],
    orderCount: 95,
    revenueGenerated: 902.5,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'dol_3',
    name: 'Tiramisu',
    category: 'dolci',
    subCategory: 'Dolci & Dessert',
    price: 9.75,
    cost: 2.2,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: false,
    isAvailable: true,
    description: '“Pick me up” — traditional espresso, savoiardi and mascarpone cream',
    allergens: ['Glutine', 'Lattosio', 'Uova'],
    orderCount: 175,
    revenueGenerated: 1706.25,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'dol_4',
    name: 'Pannacotta alla vaniglia',
    category: 'dolci',
    subCategory: 'Dolci & Dessert',
    price: 9.25,
    cost: 2.1,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: false,
    isAvailable: true,
    description: 'Vanilla pannacotta with locally sourced wild berries',
    allergens: ['Lattosio'],
    orderCount: 88,
    revenueGenerated: 814.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'dol_5',
    name: 'Tartufi di cioccolato',
    category: 'dolci',
    subCategory: 'Dolci & Dessert',
    price: 8.25,
    cost: 1.8,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: true,
    isAvailable: true,
    description: 'Selection of handmade truffles (n)',
    allergens: ['Frutta a guscio', 'Lattosio'],
    orderCount: 52,
    revenueGenerated: 429.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'dol_6',
    name: 'Biscotti (Almond Cantuccini)',
    category: 'dolci',
    subCategory: 'Dolci & Dessert',
    price: 5.75,
    cost: 1.2,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: true,
    isAvailable: true,
    description: 'Almond Cantuccini biscuits (n)',
    allergens: ['Frutta a guscio', 'Glutine', 'Uova'],
    orderCount: 65,
    revenueGenerated: 373.75,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'dol_7',
    name: 'Gelato / Sorbetto',
    category: 'dolci',
    subCategory: 'Dolci & Dessert',
    price: 7.50,
    cost: 1.6,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: false,
    isAvailable: true,
    description: "Our chef's homemade ice cream or sorbet",
    allergens: ['Lattosio'],
    orderCount: 120,
    revenueGenerated: 900.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'dol_8',
    name: 'Formaggi con marmellata di cipolle',
    category: 'dolci',
    subCategory: 'Dolci & Dessert',
    price: 12.00,
    cost: 3.8,
    destination: 'kitchen',
    isMeat: false,
    isVegetarian: true,
    containsNuts: false,
    isAvailable: true,
    description: 'Italian cheeses with red onion marmalade',
    allergens: ['Lattosio'],
    orderCount: 45,
    revenueGenerated: 540.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },

  // =========================================================================
  // 6. VINO BIANCO & ROSATO (WHITE & ROSE WINE)
  // =========================================================================
  {
    id: 'vin_w1',
    name: 'Pinot Grigio Blush, Il Sospiro - Veneto',
    category: 'vini',
    subCategory: 'Vini Bianchi & Bollicine',
    price: 39.00,
    glassPrice: 9.75,
    bottlePrice: 39.00,
    cost: 11.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Very soft with aromas of freshly crushed cranberries and mineral notes (Glass 175ml £9.75 / Btl £39.00)',
    allergens: ['Solfiti'],
    orderCount: 55,
    revenueGenerated: 2145.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_w2',
    name: 'Pinot Grigio Sartori – Veneto',
    category: 'vini',
    subCategory: 'Vini Bianchi & Bollicine',
    price: 38.00,
    glassPrice: 9.50,
    bottlePrice: 38.00,
    cost: 10.5,
    destination: 'bar',
    isAvailable: true,
    description: 'Delicate citrus perfumes, an attractive biscuit character and white floral notes on the nose (Glass 175ml £9.50 / Btl £38.00)',
    allergens: ['Solfiti'],
    orderCount: 62,
    revenueGenerated: 2356.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_w3',
    name: 'Terre del Noce Chardonnay delle Dolomiti - Trentino Alto-Adige',
    category: 'vini',
    subCategory: 'Vini Bianchi & Bollicine',
    price: 37.00,
    glassPrice: 9.25,
    bottlePrice: 37.00,
    cost: 10.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Crisp and harmonious with flavours of peach, nectarine, pear and spice (Glass 175ml £9.25 / Btl £37.00)',
    allergens: ['Solfiti'],
    orderCount: 48,
    revenueGenerated: 1776.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_w4',
    name: 'Sauvignon Blanc Borgo Tesis, Fantinel – Friuli',
    category: 'vini',
    subCategory: 'Vini Bianchi & Bollicine',
    price: 40.00,
    glassPrice: 10.00,
    bottlePrice: 40.00,
    cost: 11.5,
    destination: 'bar',
    isAvailable: true,
    description: 'Radiant white with delicate aromas of green pepper and apple, lively finish (Glass 175ml £10.00 / Btl £40.00)',
    allergens: ['Solfiti'],
    orderCount: 70,
    revenueGenerated: 2800.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_w5',
    name: 'Regaleali Bianco, Tasca – Sicilia',
    category: 'vini',
    subCategory: 'Vini Bianchi & Bollicine',
    price: 42.00,
    bottlePrice: 42.00,
    cost: 12.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Delicately fruity nose with apple, peach and pink grapefruit notes. Intense and crisp.',
    allergens: ['Solfiti'],
    orderCount: 38,
    revenueGenerated: 1596.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_w6',
    name: 'Vernaccia di San Gimignano, Teruzzi – Toscana',
    category: 'vini',
    subCategory: 'Vini Bianchi & Bollicine',
    price: 49.00,
    bottlePrice: 49.00,
    cost: 14.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Complex aromas of flowers, citrus and minerality on the nose',
    allergens: ['Solfiti'],
    orderCount: 34,
    revenueGenerated: 1666.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_w7',
    name: 'Pecorino, Fattoria La Valentina - Abruzzo',
    category: 'vini',
    subCategory: 'Vini Bianchi & Bollicine',
    price: 51.00,
    bottlePrice: 51.00,
    cost: 15.0,
    destination: 'bar',
    isAvailable: true,
    description: 'A pure yet lively aroma with mineral and lime leaf notes',
    allergens: ['Solfiti'],
    orderCount: 40,
    revenueGenerated: 2040.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_w8',
    name: 'Gavi di Gavi La Meirana, Broglia – Piemonte',
    category: 'vini',
    subCategory: 'Vini Bianchi & Bollicine',
    price: 54.00,
    bottlePrice: 54.00,
    cost: 16.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Great texture and precision with distinctive greenage and almond notes',
    allergens: ['Solfiti'],
    orderCount: 45,
    revenueGenerated: 2430.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_w9',
    name: 'Roero Arneis Serra Lupini, Azienda Agricola Negro – Piemonte',
    category: 'vini',
    subCategory: 'Vini Bianchi & Bollicine',
    price: 58.00,
    bottlePrice: 58.00,
    cost: 17.5,
    destination: 'bar',
    isAvailable: true,
    description: 'Developed roundness with a hint of peach stone and a creamy texture',
    allergens: ['Solfiti'],
    orderCount: 29,
    revenueGenerated: 1682.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_w10',
    name: 'Pinot Grigio Pian del Griso, Bossi Fedrigotti – Trentino Alto-Adige',
    category: 'vini',
    subCategory: 'Vini Bianchi & Bollicine',
    price: 61.00,
    bottlePrice: 61.00,
    cost: 18.5,
    destination: 'bar',
    isAvailable: true,
    description: 'Strong minerality with delicate floral notes and hints of peaches and plums',
    allergens: ['Solfiti'],
    orderCount: 32,
    revenueGenerated: 1952.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_w11',
    name: 'Chardonnay Bramito del Cervo, Castello della Sala – Umbria',
    category: 'vini',
    subCategory: 'Vini Bianchi & Bollicine',
    price: 67.00,
    bottlePrice: 67.00,
    cost: 21.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Richly structured palate and aromas of apples and vanilla (Antinori)',
    allergens: ['Solfiti'],
    orderCount: 36,
    revenueGenerated: 2412.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_w12',
    name: 'Sauvignon Blanc Conte della Vipera, Castello della Sala – Umbria',
    category: 'vini',
    subCategory: 'Vini Bianchi & Bollicine',
    price: 75.00,
    bottlePrice: 75.00,
    cost: 24.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Rich Sauvignon Blanc with citrus aromas, herbs and nuts',
    allergens: ['Solfiti'],
    orderCount: 22,
    revenueGenerated: 1650.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },

  // =========================================================================
  // 7. VINO ROSSO (RED WINE)
  // =========================================================================
  {
    id: 'vin_r1',
    name: 'Terre del Noce Merlot delle Dolomiti, 2024/25 – Trentino Alto-Adige',
    category: 'vini',
    subCategory: 'Vini Rossi',
    price: 37.00,
    glassPrice: 9.25,
    bottlePrice: 37.00,
    cost: 10.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Smooth with plum and red cherry fruit with a hint of dark chocolate on the finish (Glass 175ml £9.25 / Btl £37.00)',
    allergens: ['Solfiti'],
    orderCount: 68,
    revenueGenerated: 2516.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_r2',
    name: 'Syrah, Molino a Vento, 2024/25 – Sicilia',
    category: 'vini',
    subCategory: 'Vini Rossi',
    price: 39.00,
    glassPrice: 9.75,
    bottlePrice: 39.00,
    cost: 11.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Dry, ripe fruit taste with blackberry, blueberry and pepper (Glass 175ml £9.75 / Btl £39.00)',
    allergens: ['Solfiti'],
    orderCount: 52,
    revenueGenerated: 2028.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_r3',
    name: 'Montepulciano d’Abruzzo, Itynera, 2024/25 – Abruzzo',
    category: 'vini',
    subCategory: 'Vini Rossi',
    price: 40.00,
    glassPrice: 10.00,
    bottlePrice: 40.00,
    cost: 11.5,
    destination: 'bar',
    isAvailable: true,
    description: 'Rich in notes of ripe berries, cocoa and vanilla (Glass 175ml £10.00 / Btl £40.00)',
    allergens: ['Solfiti'],
    orderCount: 75,
    revenueGenerated: 3000.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_r4',
    name: 'Cabernet Sauvignon Castel Firmian, Mezzacorona 2023/24 – Trentino Alto-Adige',
    category: 'vini',
    subCategory: 'Vini Rossi',
    price: 42.00,
    bottlePrice: 42.00,
    cost: 12.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Intense, complex flavour with spicy notes and sweet fruit with a fragrant scent of oak. Well balanced and full bodied',
    allergens: ['Solfiti'],
    orderCount: 44,
    revenueGenerated: 1848.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_r5',
    name: 'Valpolicella Ripasso, Bertani 2022/23– Veneto',
    category: 'vini',
    subCategory: 'Vini Rossi',
    price: 52.00,
    bottlePrice: 52.00,
    cost: 15.5,
    destination: 'bar',
    isAvailable: true,
    description: 'Clean and intense aroma of ripe red fruit with hints of bramble, blackcurrant and ripe cherry',
    allergens: ['Solfiti'],
    orderCount: 60,
    revenueGenerated: 3120.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_r6',
    name: 'Primitivo della Puglia, Botromagno 2023/24 – Puglia',
    category: 'vini',
    subCategory: 'Vini Rossi',
    price: 55.00,
    bottlePrice: 55.00,
    cost: 16.5,
    destination: 'bar',
    isAvailable: true,
    description: 'The palate is elegant and intense with soft natural tannins',
    allergens: ['Solfiti'],
    orderCount: 65,
    revenueGenerated: 3575.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_r7',
    name: 'Chianti Classico Peppoli, Antinori 2023/24 – Toscana',
    category: 'vini',
    subCategory: 'Vini Rossi',
    price: 58.00,
    bottlePrice: 58.00,
    cost: 17.5,
    destination: 'bar',
    isAvailable: true,
    description: 'Intense red fruit aromas are offset by delicate notes of vanilla and chocolate',
    allergens: ['Solfiti'],
    orderCount: 82,
    revenueGenerated: 4756.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_r8',
    name: 'Pinot Noir Focara, Fattoria Mancini 2021/22 – Marche',
    category: 'vini',
    subCategory: 'Vini Rossi',
    price: 68.00,
    bottlePrice: 68.00,
    cost: 21.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Creamy strawberry/redcurrant aromas. Midweight and elegant',
    allergens: ['Solfiti'],
    orderCount: 28,
    revenueGenerated: 1904.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_r9',
    name: 'Barolo, Prunotto 2021/22 - Piemonte',
    category: 'vini',
    subCategory: 'Vini Rossi',
    price: 87.00,
    bottlePrice: 87.00,
    cost: 28.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Forest fruits character with floral and smoky finish (Prunotto / Antinori)',
    allergens: ['Solfiti'],
    orderCount: 48,
    revenueGenerated: 4176.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_r10',
    name: 'Brunello di Montalcino, Il Poggione 2019 – Toscana',
    category: 'vini',
    subCategory: 'Vini Rossi',
    price: 90.00,
    bottlePrice: 90.00,
    cost: 29.0,
    destination: 'bar',
    isAvailable: true,
    description: 'A very intense, lingering and stylish bouquet with small dark berry fruit notes',
    allergens: ['Solfiti'],
    orderCount: 35,
    revenueGenerated: 3150.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_r11',
    name: 'Amarone della Valpolicella Classico, Costasera Masi 2020/21 – Veneto',
    category: 'vini',
    subCategory: 'Vini Rossi',
    price: 100.00,
    bottlePrice: 100.00,
    cost: 32.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Preserved cherries and dried plums together with hints of fruits of the forest and cinnamon',
    allergens: ['Solfiti'],
    orderCount: 30,
    revenueGenerated: 3000.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_r12',
    name: 'Tignanello, Antinori 2020/21 – Toscana',
    category: 'vini',
    subCategory: 'Vini Rossi',
    price: 230.00,
    bottlePrice: 230.00,
    cost: 85.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Iconic Super Tuscan. Ripe red fruit and spice aromas, as well as vanilla and oaky notes',
    allergens: ['Solfiti'],
    orderCount: 18,
    revenueGenerated: 4140.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },

  // =========================================================================
  // 8. PROSECCO & CHAMPAGNE
  // =========================================================================
  {
    id: 'vin_sp1',
    name: 'Prosecco Brut di Valdobbiadene, Argeo Ruggeri – Veneto',
    category: 'vini',
    subCategory: 'Prosecco & Champagne',
    price: 66.00,
    glassPrice: 12.00,
    bottlePrice: 66.00,
    cost: 16.0,
    destination: 'bar',
    isAvailable: true,
    description: 'A palate of fresh green apple and a long, crisp finish (Glass 125ml £12.00 / Btl £66.00)',
    allergens: ['Solfiti'],
    orderCount: 88,
    revenueGenerated: 5808.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_sp2',
    name: 'Champagne Jacquart Brut Mosaïque – France',
    category: 'vini',
    subCategory: 'Prosecco & Champagne',
    price: 96.00,
    glassPrice: 17.00,
    bottlePrice: 96.00,
    cost: 28.0,
    destination: 'bar',
    isAvailable: true,
    description: 'The bouquet is fresh with pear hints. Long-lasting finish of spice bread and fruit flavours (Glass 125ml £17.00 / Btl £96.00)',
    allergens: ['Solfiti'],
    orderCount: 42,
    revenueGenerated: 4032.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_sp3',
    name: 'Champagne Jacquart Rosé Mosaïque – France',
    category: 'vini',
    subCategory: 'Prosecco & Champagne',
    price: 96.00,
    glassPrice: 17.00,
    bottlePrice: 96.00,
    cost: 29.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Pink fizz that bubbles with ripe redcurrants, cherries, wild strawberries and plums (Glass 125ml £17.00 / Btl £96.00)',
    allergens: ['Solfiti'],
    orderCount: 30,
    revenueGenerated: 2880.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
  {
    id: 'vin_sp4',
    name: 'Dom Perignon Vintage',
    category: 'vini',
    subCategory: 'Prosecco & Champagne',
    price: 250.00,
    bottlePrice: 250.00,
    cost: 95.0,
    destination: 'bar',
    isAvailable: true,
    description: 'Prestige Cuvée Champagne. Exceptional depth, minerality and refined brioche nuances.',
    allergens: ['Solfiti'],
    orderCount: 12,
    revenueGenerated: 3000.0,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-10-06T00:00:00Z',
  },
];

export const menuService = {
  getItems(): MenuItem[] {
    const raw = localStorage.getItem(MENU_STORAGE_KEY);
    if (raw) {
      try {
        const parsed = JSON.parse(raw);
        if (Array.isArray(parsed) && parsed.length > 0) {
          return parsed;
        }
      } catch (e) {
        console.error('Failed to parse menu items from storage', e);
      }
    }
    localStorage.setItem(MENU_STORAGE_KEY, JSON.stringify(INITIAL_MENU_ITEMS));
    return INITIAL_MENU_ITEMS;
  },

  saveItems(items: MenuItem[]): void {
    localStorage.setItem(MENU_STORAGE_KEY, JSON.stringify(items));
  },

  getItemById(id: string): MenuItem | undefined {
    return this.getItems().find((item) => item.id === id);
  },

  toggleAvailability(id: string): MenuItem[] {
    const items = this.getItems().map((item) => {
      if (item.id === id) {
        return {
          ...item,
          isAvailable: !item.isAvailable,
          updatedAt: new Date().toISOString(),
        };
      }
      return item;
    });
    this.saveItems(items);
    return items;
  },

  addItem(newItem: Omit<MenuItem, 'id' | 'orderCount' | 'revenueGenerated' | 'createdAt' | 'updatedAt'>): MenuItem {
    const items = this.getItems();
    const created: MenuItem = {
      ...newItem,
      id: `menu_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
      orderCount: 0,
      revenueGenerated: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    items.unshift(created);
    this.saveItems(items);
    return created;
  },

  updateItem(id: string, updates: Partial<MenuItem>): MenuItem[] {
    const items = this.getItems().map((item) => {
      if (item.id === id) {
        return {
          ...item,
          ...updates,
          updatedAt: new Date().toISOString(),
        };
      }
      return item;
    });
    this.saveItems(items);
    return items;
  },

  deleteItem(id: string): MenuItem[] {
    const items = this.getItems().filter((item) => item.id !== id);
    this.saveItems(items);
    return items;
  },

  getTopSellers(limit = 5, categoryType: 'food' | 'beverage' = 'food'): MenuItem[] {
    const items = this.getItems();
    const filtered = items.filter((item) => {
      if (categoryType === 'food') {
        return item.category === 'a_la_carte' || item.category === 'dolci' || item.category === 'fuori_menu';
      } else {
        return item.category === 'vini' || item.category === 'bibite';
      }
    });

    return filtered.sort((a, b) => b.orderCount - a.orderCount).slice(0, limit);
  },

  getLowSellers(limit = 5, categoryType: 'food' | 'beverage' = 'food'): MenuItem[] {
    const items = this.getItems();
    const filtered = items.filter((item) => {
      if (categoryType === 'food') {
        return item.category === 'a_la_carte' || item.category === 'dolci' || item.category === 'fuori_menu';
      } else {
        return item.category === 'vini' || item.category === 'bibite';
      }
    });

    return filtered.sort((a, b) => a.orderCount - b.orderCount).slice(0, limit);
  },

  recordItemOrder(id: string, quantity = 1): void {
    const items = this.getItems().map((item) => {
      if (item.id === id) {
        return {
          ...item,
          orderCount: (item.orderCount || 0) + quantity,
          revenueGenerated: (item.revenueGenerated || 0) + (item.price || 0) * quantity,
          updatedAt: new Date().toISOString(),
        };
      }
      return item;
    });
    this.saveItems(items);
  },
};
